##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  vars:
    php_version: '7.2'
    php_default_version_debian: '7.2'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
